version: '3.9'

services:
  server:
    image: ghcr.io/chroma-core/chroma:0.5.23
    hostname: chromadb
    environment:
      - IS_PERSISTENT=TRUE
    volumes:
      - chroma-data:/chroma/chroma/
    ports:
      - 8000:8000

volumes:
  chroma-data:
    driver: local
