# Use root/example as user/password credentials
services:

  db:
    image: mysql:9.3.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example
    # (this is just an example, not intended to be a production configuration)
    volumes:
      - mysql-data:/var/lib/mysql
    ports:
      - 3306:3306


volumes:
  mysql-data:
    driver: local